## AlphabetSoupCharity_Optimisation: Preprocessing

In [316]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import sklearn as skl

#  Import and read the charity_data.csv.
import pandas as pd 
Application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
Application_df.head(10)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
5,10556855,MINORITY ORGAN & TISSUE TRANSPLANT & EDUCATION...,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
6,10558440,FRIENDS OF ARTS COUNCIL OF GREATER DENHAM SPRI...,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31452,1
7,10566033,ISRAEL EMERGENCY ALLIANCE,T3,Independent,C2000,Preservation,Trust,1,10M-50M,N,7508025,1
8,10570430,ARAMCO BRATS INC,T7,Independent,C1000,ProductDev,Trust,1,1-9999,N,94389,1
9,10571689,INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0

In [ ]:
# Drop the non-beneficial ID columns, 'EIN','NAME', and 'INCOME_AMT'

Application_df = Application_df.drop(columns=['EIN','NAME','SPECIAL_CONSIDERATIONS','INCOME_AMT'])
Application_df.head()

In [ ]:
# Determine the number of unique values in each column.

unique_counts = Application_df.nunique()
print(unique_counts)

In [279]:
# Look at APPLICATION_TYPE value counts for binning
Application_type_counts =  Application_df['APPLICATION_TYPE'].value_counts()
print(Application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [280]:
# Choose a cutoff value. cutoff incresed from 500 to 1000
cutoff_value = 1000

# Create a list of application types to be replaced
Application_types_to_replace = Application_type_counts[Application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in Application_types_to_replace:
    Application_df['APPLICATION_TYPE'] = Application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure binning was successful
Application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [281]:
# Look at CLASSIFICATION value counts for binning

classification_counts =  Application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [251]:
# You may find it helpful to look at CLASSIFICATION value counts >1
print(classification_counts[classification_counts > 1])

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [282]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1000
# Create a list of classification to be replaced
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    Application_df['CLASSIFICATION'] = Application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
Application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [283]:
# Determine categorcal variables in dataframe
Application_df.dtypes

APPLICATION_TYPE    object
AFFILIATION         object
CLASSIFICATION      object
USE_CASE            object
ORGANIZATION        object
STATUS               int64
INCOME_AMT          object
ASK_AMT              int64
IS_SUCCESSFUL        int64
dtype: object

In [324]:
# Convert categorical data to numeric with `pd.get_dummies`
Application_numeric = pd.get_dummies(Application_df)


Application_numeric.head()

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,10531628,1,108590,1,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,10547893,1,5000,0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,10553066,1,6692,1,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,10556103,1,142590,1,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [325]:
# Split our preprocessed data into our features and target arrays
y= Application_numeric["IS_SUCCESSFUL"].values
X= Application_numeric.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset. random_state  reduced
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=58)

KeyboardInterrupt:

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
print(X_train_scaled.shape)

## Compile, Train and Evaluate the Model

In [311]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=38))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation="relu"))

# third hidden layer
nn.add(tf.keras.layers.Dense(units=40, activation="relu"))

# fourth hidden layer
nn.add(tf.keras.layers.Dense(units=40, activation="relu"))

# fifth hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

C:\Users\karun\AppData\Local\conda\conda\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_44"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_188 (Dense)                    │ (None, 80)                  │           3,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_189 (Dense)                    │ (None, 50)                  │           4,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_190 (Dense)                    │ (None, 40)                  │           2,040 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_191 (Dense)                    │ (None, 40)                  │           1,640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_192 (Dense)                    │ (None, 30)                  │           1,230 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_193 (Dense)                    │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 12,111 (47.31 KB)

 Trainable params: 12,111 (47.31 KB)

 Non-trainable params: 0 (0.00 B)

In [312]:
# Compile the model
# nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
# Define the optimizer with a custom learning rate
custom_optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)

# Compile the model with the custom optimizer
nn.compile(loss="binary_crossentropy", optimizer=custom_optimizer, metrics=["accuracy"])

In [313]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=40,  batch_size=38)

Epoch 1/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6544 - loss: 0.6530
Epoch 2/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7254 - loss: 0.5674
Epoch 3/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7309 - loss: 0.5572
Epoch 4/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7263 - loss: 0.5584
Epoch 5/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7334 - loss: 0.5527
Epoch 6/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7351 - loss: 0.5515
Epoch 7/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7332 - loss: 0.5515
Epoch 8/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7296 - loss: 0.5555
Epoch 9/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7282 - loss: 0.5522
Epoch 10/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7331 - loss: 0.5500
Epoch 11/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7345 - loss: 0.5474
Epoch 12/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7338 - loss: 0.5486
Epoch 13/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7400 - loss: 0.5412
Epoch 14/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7362 - loss: 0.5490
Epoch 15/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7367 - loss: 0.5463
Epoch 16/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7374 - loss: 0.5446
Epoch 17/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7357 - loss: 0.5490
Epoch 18/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7409 - loss: 0.5406
Epoch 19/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7366 - loss: 0.5468
Epoch 20/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7418 - loss: 0.5398
Epoch 21/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7351 - loss: 0.5476
Epoch 22/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7385 - loss: 0.5441
Epoch 23/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7439 - loss: 0.5420
Epoch 24/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7411 - loss: 0.5400
Epoch 25/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7397 - loss: 0.5417
Epoch 26/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7315 - loss: 0.5486
Epoch 27/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7385 - loss: 0.5427
Epoch 28/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7387 - loss: 0.5437
Epoch 29/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7371 - loss: 0.5466
Epoch 30/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7365 - loss: 0.5415
Epoch 31/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7356 - loss: 0.5459
Epoch 32/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7435 - loss: 0.5384
Epoch 33/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7415 - loss: 0.5405
Epoch 34/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7379 - loss: 0.5449
Epoch 35/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7390 - loss: 0.5408
Epoch 36/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7377 - loss: 0.5449
Epoch 37/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7435 - loss: 0.5396
Epoch 38/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7355 - loss: 0.5459
Epoch 39/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7385 - loss: 0.5421
Epoch 40/40
677/677 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7390 - loss: 0.5411

In [314]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.7263 - loss: 0.5542
Loss: 0.554248571395874, Accuracy: 0.7262973785400391

In [50]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.